import { StyleAst } from "shared/types/frameExec";

export const defaultStyleAst: StyleAst = {
  sem: 'root',
  type: 'style',
  selector: '',
  styles: {},
  children: [
    {
      sem: 'h1',
      type: 'style',
      selector: '',
      styles: {
        '--font-text-size': 'var(--h1-size)',
        '--font-text-weight': 'var(--h1-weight)',
        'color': 'var(--h1-color)',
      },
      children: [],
    },
    {
      sem: 'h2',
      type: 'style',
      selector: '',
      styles: {
        '--font-text-size': 'var(--h2-size)',
        '--font-text-weight': 'var(--h2-weight)',
        'color': 'var(--h2-color)',
      },
      children: [],
    },
    {
      sem: 'h3',
      type: 'style',
      selector: '',
      styles: {
        '--font-text-size': 'var(--h3-size)',
        '--font-text-weight': 'var(--h3-weight)',
        'color': 'var(--h3-color)',
      },
      children: [],
    },
    {
      sem: 'h4',
      type: 'style',
      selector: '',
      styles: {
        '--font-text-size': 'var(--h4-size)',
        '--font-text-weight': 'var(--h4-weight)',
        'color': 'var(--h4-color)',
      },
      children: [],
    },
    {
      sem: 'h5',
      type: 'style',
      selector: '',
      styles: {
        '--font-text-size': 'var(--h5-size)',
        '--font-text-weight': 'var(--h5-weight)',
        'color': 'var(--h5-color)',
      },
      children: [],
    },
    {
      sem: 'h6',
      type: 'style',
      selector: '',
      styles: {
        '--font-text-size': 'var(--h6-size)',
        '--font-text-weight': 'var(--h6-weight)',
        'color': 'var(--h6-color)',
      },
      children: [],
    },
    {
      sem: 'button',
      type: 'style',
      selector: '',
      styles: {
        color: 'var(--text-color)',
        backgroundColor: 'var(--interactive-normal)',
        boxShadow: 'var(--input-shadow)',
        fontSize: 'var(--font-ui-small)',
        borderRadius: 'var(--button-radius)',
        padding: 'var(--size-4-1) var(--size-4-3)',
        height: 'var(--input-height)',
        fontWeight: 'var(--input-font-weight)',
        cursor: 'var(--cursor)',
        display: 'flex',
        alignItems: 'center',
        transition: 'all 0.15s ease',
        'hover:backgroundColor': 'var(--interactive-hover)',
        'press:backgroundColor': 'var(--interactive-accent)',
        'focus:outline': '2px solid var(--interactive-accent)',
        'focus:outlineOffset': '2px',
        'disabled:opacity': '0.6',
        'disabled:cursor': 'not-allowed',
      },
      children: [],
    },
    {
      sem: 'card',
      type: 'style',
      selector: '',
      styles: {
        borderRadius: '10px',
        background: 'var(--mk-ui-background)',
        width: 'auto',
        layout: 'column',
        height: 'auto',
        padding: '16px',
       border: '1px solid var(--mk-ui-border)',
        boxShadow: 'var(--mk-shadow-card)',
        transition: 'all 0.15s ease',
      },
      children: [],
    },
    {
      sem: 'card-selected',
      type: 'style',
      selector: '',
      styles: {
        borderRadius: '10px',
        background: 'var(--mk-ui-background-selected)',
        width: 'auto',
        layout: 'column',
        height: 'auto',
        padding: '16px',
       border: '1px solid var(--mk-ui-border)',
        boxShadow: 'var(--mk-shadow-card)',
        transition: 'all 0.15s ease',
      },
      children: [],
    },
    {
      sem: 'a',
      type: 'style',
      selector: '',
      styles: {
        layout: 'row',
        gap: '4px',
        cursor: 'pointer',
        transition: 'all 0.15s ease',
        textDecoration: 'none',
        'hover:textDecoration': 'underline',
        'hover:color': 'var(--interactive-accent)',
        'press:transform': 'translateX(0px)',
        'focus:outline': '2px solid var(--interactive-accent)',
        'focus:outlineOffset': '2px',
      },
      children: [],
    },
    {
      sem: 'tab',
      type: 'style',
      selector: '',
      styles: {
        padding: '4px 8px',
        borderRadius: '4px 4px 0 0',
        cursor: 'pointer',
        transition: 'all 0.15s ease',
        color: 'var(--text-muted)',
        backgroundColor: 'transparent',
        borderBottom: '2px solid transparent',
        'hover:color': 'var(--text-normal)',
      },
      children: [],
    },
    {
      sem: 'tab-active',
      type: 'style',
      selector: '',
      styles: {
        padding: '4px 8px',
        borderRadius: '4px 4px 0 0',
        cursor: 'pointer',
        transition: 'all 0.15s ease',
        color: 'var(--text-normal)',
        borderBottom: '2px solid var(--interactive-accent)',
        'hover:color': 'var(--text-normal)',
        'press:backgroundColor': 'var(--background-modifier-active-hover)',
        'press:transform': 'translateY(0px)',
        'focus:outline': '2px solid var(--interactive-accent)',
        'focus:outlineOffset': '2px',
      },
      children: [],
    },
  ],
};