import { MakeMDSettings } from "../types/settings";



export const DEFAULT_SETTINGS: MakeMDSettings = {
  newNotePlaceholder: 'Untitled',
  defaultInitialization: false,
  filePreviewOnHover: false,
  flowMenuEnabled: true,
  markSans: false,
  blinkEnabled: true,
  makeMenuPlaceholder: true,
  mobileMakeBar: true,
  inlineStyler: true,
  makerMode: true,
  spacesMDBInHidden: true,
  inlineStylerColors: false,
  editorFlow: true,
  internalLinkClickFlow: true,
  contextEnabled: true,
  spaceViewEnabled: true,
  saveAllContextToFrontmatter: true,
  editorFlowStyle: "seamless",
  autoOpenFileContext: false,
  activeView: "Spaces/Home",
  hideFrontmatter: true,
  activeSpace: "",
  defaultDateFormat: "MMM dd yyyy",
  spacesEnabled: true,
  spacesPerformance: false,
  enableFolderNote: true,
  folderIndentationLines: true,
  revealActiveFile: false,
  spacesStickers: true,
  spaceRowHeight: 29,
  spacesDisablePatch: false,
  folderNoteInsideFolder: true,
  sidebarTabs: true,
  showRibbon: true,
  deleteFileOption: "trash",
  expandedSpaces: ["/"],
  expandFolderOnClick: true,
  menuTriggerChar: "/",
  inlineStickerMenu: true,
  emojiTriggerChar: ":",
  folderContextFile: "context",
  folderFrameFile: "frames",
  spacesFolder: "Spaces",
  hiddenFiles: [],
  hiddenExtensions: [".mdb"],
  newFileLocation: "root",
  newFileFolderPath: "",
  inlineBacklinks: false,
  inlineContext: true,
  inlineBacklinksExpanded: false,
  inlineContextExpanded: true,
  inlineContextSectionsExpanded: true,
  dataviewInlineContext: false,
  inlineContextNameLayout: "vertical",
  waypoints: ['Spaces/Home', '/', 'spaces://$tags'],
  spacesUseAlias: false,
  fmKeyAlias: 'aliases',
  fmKeyBanner: 'banner',
  fmKeyColor: 'color',
  fmKeySticker: 'sticker',
  fmKeyContexts: '_contexts',
  fmKeySort: '_sort',
  fmKeyFilter: '_filters',
  fmKeyLinks: '_links',
  openSpacesOnLaunch: true,
  indexSVG: false,
  quickFrames: [],
  readableLineWidth: true,
  autoAddContextsToSubtags: true,
  autoMigration08: false,
  releaseNotesPrompt: 0.8,
  enableDefaultSpaces: true,
  enableTagSpaces: true,
  enableHomeSpace: true,
  showSpacePinIcon: true,
  minimalFix: false,
  experimental: false,
  systemName: "Vault"
};
